name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.changes.outputs.client }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

  test:
    if: needs.changes.outputs.client == 'true'
    name: JS Client
    needs: changes
    uses: ./.github/workflows/test.yml
    secrets: inherit
